---
title: "TransComp-R Proteomics Analysis SCI & SHAM"
author: "Brendan K. Ball"
date: "2025-12-18"
output: html_document
---

# 1. PACKAGES IMPORT
```{r Import Required Packages}
# Downloads and calls from the library the necessary packages needed to run the code
# Downloads and calls from the library the necessary packages needed to run the code
if(!require(stringr)) install.packages("stringr", repos = "http://cran.us.r-project.org")
suppressWarnings(library (stringr, verbose = FALSE))
if(!require(gtools)) install.packages("gtools", repos = "http://cran.us.r-project.org")
suppressWarnings(library (gtools, verbose = FALSE))
if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
suppressWarnings(library (dplyr, verbose = FALSE))
if(!require(factoextra)) install.packages("factoextra", repos = "http://cran.us.r-project.org")
suppressWarnings(library (factoextra, verbose = FALSE))
if(!require(devtools)) install.packages("devtools", repos = "http://cran.us.r-project.org")
suppressWarnings(library (devtools, verbose = FALSE))
if(!require(data.table)) install.packages("data.table", repos = "http://cran.us.r-project.org")
suppressWarnings(library (data.table, verbose = FALSE))
if(!require(tibble)) install.packages("tibble", repos = "http://cran.us.r-project.org")
suppressWarnings(library (tibble, verbose = FALSE))
if(!require(lme4)) install.packages("lme4", repos = "http://cran.us.r-project.org")
suppressWarnings(library (lme4, verbose = FALSE))
if(!require(emmeans)) install.packages("emmeans", repos = "http://cran.us.r-project.org")
suppressWarnings(library (emmeans, verbose = FALSE))
if(!require(effects)) install.packages("effects", repos = "http://cran.us.r-project.org")
suppressWarnings(library (effects, verbose = FALSE))
if(!require(ggforce)) install.packages("ggforce", repos = "http://cran.us.r-project.org")
suppressWarnings(library (ggforce, verbose = FALSE))
if(!require(pheatmap)) install.packages("pheatmap", repos = "http://cran.us.r-project.org")
suppressWarnings(library (pheatmap, verbose = FALSE))
if(!require(limma)) install.packages("limma", repos = "http://cran.us.r-project.org")
suppressWarnings(library (limma, verbose = FALSE))
if(!require(umap)) install.packages("umap", repos = "http://cran.us.r-project.org")
suppressWarnings(library (umap, verbose = FALSE))
if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
suppressWarnings(library (dplyr, verbose = FALSE))
if(!require(stringr)) install.packages("stringr", repos = "http://cran.us.r-project.org")
suppressWarnings(library (stringr, verbose = FALSE))
if(!require(powerjoin)) install.packages("powerjoin", repos = "http://cran.us.r-project.org")
suppressWarnings(library (powerjoin, verbose = FALSE))
if(!require(tidyr)) install.packages("tidyr", repos = "http://cran.us.r-project.org")
suppressWarnings(library (tidyr, verbose = FALSE))
if(!require(purrr)) install.packages("purrr", repos = "http://cran.us.r-project.org")
suppressWarnings(library (purrr, verbose = FALSE))
if(!require(fgsea)) install.packages("fgsea", repos = "http://cran.us.r-project.org")
suppressWarnings(library (fgsea, verbose = FALSE)) # Imported using BiocManager::install("fgsea")
if(!require(glmnet)) install.packages("glmnet", repos = "http://cran.us.r-project.org")
suppressWarnings(library (glmnet, verbose = FALSE))
if(!require(tidyverse)) install.packages("tidyverse", repos = "http://cran.us.r-project.org")
suppressWarnings(library (tidyverse, verbose = FALSE))
if(!require(orthogene)) install.packages("orthogene", repos = "http://cran.us.r-project.org")
suppressWarnings(library (orthogene, verbose = FALSE))
if(!require(openxlsx)) install.packages("openxlsx", repos = "http://cran.us.r-project.org")
suppressWarnings(library (openxlsx, verbose = FALSE))
if(!require(ggpubr)) install.packages("ggpubr", repos = "http://cran.us.r-project.org")
suppressWarnings(library (ggpubr, verbose = FALSE))
if(!require(writexl)) install.packages("writexl", repos = "http://cran.us.r-project.org")
suppressWarnings(library (writexl, verbose = FALSE))
if (!require("msigdbr")) {BiocManager::install("msigdbr")}
suppressWarnings(library (msigdbr, verbose = FALSE))
if(!require(reshape2)) install.packages("reshape2", repos = "http://cran.us.r-project.org")
suppressWarnings(library (reshape2, verbose = FALSE))
if (!require("AnnotationDbi")) {BiocManager::install("AnnotationDbi")}
suppressWarnings(library (AnnotationDbi, verbose = FALSE))
if(!require(ggraph)) install.packages("ggraph", repos = "http://cran.us.r-project.org")
suppressWarnings(library (ggraph, verbose = FALSE))
if(!require(igraph)) install.packages("igraph", repos = "http://cran.us.r-project.org")
suppressWarnings(library (igraph, verbose = FALSE))
if(!require(tidygraph)) install.packages("tidygraph", repos = "http://cran.us.r-project.org")
suppressWarnings(library (tidygraph, verbose = FALSE))
if(!require(VennDiagram)) install.packages("VennDiagram", repos = "http://cran.us.r-project.org")
suppressWarnings(library (VennDiagram, verbose = FALSE))
if(!require(VIM)) install.packages("VIM", repos = "http://cran.us.r-project.org")
suppressWarnings(library (VIM, verbose = FALSE)) 
if(!require(circlize)) install.packages("circlize", repos = "http://cran.us.r-project.org")
suppressWarnings(library (circlize, verbose = FALSE))
if(!require(plotly)) install.packages("plotly", repos = "http://cran.us.r-project.org")
suppressWarnings(library (plotly, verbose = FALSE))

# Bioconductor
if (!requireNamespace('BiocManager', quietly = TRUE))
  install.packages('BiocManager')
BiocManager::install("org.Rn.eg.db")
library(org.Rn.eg.db)
BiocManager::install("org.Hs.eg.db")
library(org.Hs.eg.db)
BiocManager::install("sva")
library("sva")
BiocManager::install("EnrichmentBrowser")
library(EnrichmentBrowser)
BiocManager::install("mixOmics")
library(mixOmics)
BiocManager::install("clusterProfiler")
library(clusterProfiler)
BiocManager::install("EnhancedVolcano")
library(EnhancedVolcano)
```

```{r Data Download}
# download the data
SCI_dat <- read.csv("SCI_gsea_dat_list_stats_filt.csv")
ACR_dat <- read.csv("ACR_gsea_dat_list_stats_filt.csv")
```

```{r Pre-Processing}
# Pull out the geneID and convert to matrix fornat
SCI_dat <- SCI_dat %>% select(GeneID, sham_1, sham_2, sham_3, sham_4, sham_5, sci_1, sci_2, sci_3, sci_4, sci_5)
SCI_dat <- SCI_dat %>% column_to_rownames(var="GeneID")

ACR_dat <- ACR_dat %>% select(GeneID, saline_1, saline_2, saline_3, saline_4, saline_5, acrolein_1, acrolein_2, acrolein_3, acrolein_4, acrolein_5)
ACR_dat <- ACR_dat %>% column_to_rownames(var="GeneID")
# Take the transpose
SCI_dat_t <- t(SCI_dat)
ACR_dat_t <- t(ACR_dat)
# Collect only genes that match 1:1
col_extracted <- intersect(colnames(SCI_dat_t), colnames(ACR_dat_t))
# Keep genes that are only shared across the datasets
SCI_dat_int <- SCI_dat_t[,col_extracted]
ACR_dat_int <- ACR_dat_t[,col_extracted]
# Function to calculate z-score for a vector
calc_z_score <- function(x) {
  (x - mean(x)) / sd(x)
}
# Loop through each column and apply the z-score transformation 
for (i in 1:ncol(ACR_dat_int)) {
  ACR_dat_int[,i] <- calc_z_score(ACR_dat_int[,i])
}
# Loop through each column and apply the z-score transformation
for (i in 1:ncol(SCI_dat_int)) {
  SCI_dat_int[,i] <- calc_z_score(SCI_dat_int[,i])
}
```

```{r PCA and PC Preparation}
X_ACR_dat <- ACR_dat_int
X_ACR_dat_t <- t(X_ACR_dat)
X_ACR_dat_t <- as.data.frame(X_ACR_dat_t)
X_ACR_dat_t <- tibble::rownames_to_column(X_ACR_dat_t, var = "GeneID")
# Prepare the principal component analysis
Q_ACRdat_pr <- prcomp(X_ACR_dat_t[c(2:(ncol(X_ACR_dat_t)))], center = TRUE, scale = FALSE)
# Prepare the Scree Plot
screeplot(Q_ACRdat_pr, type = "l", npcs = 10, main = "Scree Plot of the 10PCs")
abline(h = 1, col="red", lty=20)
legend("topright", legend=c("Eigenvalue = 1"),
       col=c("red"), lty=5, cex=0.6)
# Cumulative Variance Plot for 80% Variance
cumVar <- cumsum(Q_ACRdat_pr$sdev^2 / sum(Q_ACRdat_pr$sdev^2))
#svg('cumulativeVarPlot.svg', width = 4, height = 4)
plot(cumVar[0:10], xlab = "Principle Component #", ylab = "Amount of Explained Variance", main = "Cumulative Variance Plot")
abline(v = 6, col="blue", lty=5)
abline(h = 0.80, col="blue", lty=5)
legend("bottomright", legend=c("Cut-off @ PC6"),
       col=c("blue"), lty=5, cex=0.6)
#dev.off()
# Identify number of PCs => 80%
print(c("Princial components at 80% variance is:", which(cumVar >= 0.80)[1]))
PC_80_val <- as.numeric(which(cumVar >= 0.80)[1])

# Recreate the cumulative variance plot for thematic purposes
cumvarplot <- data.frame(PC = 0:8, Variance = cumVar[0:8 + 1])  # R uses 1-based indexing
cumvarplot$PC <- cumvarplot$PC + 1
# Create the ggplot
cumVarPlot <- ggplot(cumvarplot, aes(x = PC, y = Variance)) +
  geom_line() +
  geom_point() +
  geom_vline(xintercept = 6, color = "black", linetype = "dashed") +
  geom_hline(yintercept = 0.80, color = "black", linetype = "dashed") +
  labs(
    x = "Principal Component #",
    y = "Cumulative Variance Explained"
  ) +
  theme_bw() +
    theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) + xlim(0,13)
#ggsave("cumVarPlot.svg", plot = cumVarPlot, width = 6, height = 4, units = "in")
```

```{r TransComp-R}
# Collect the PCs of the rat data set
Q_ACR <- Q_ACRdat_pr$x
# Extract PC1 to PCs that represent 80% explained variability
Q_ACR <-  Q_ACR[, c(1:PC_80_val)]
# Keep row names as the gene identifiers
rownames(Q_ACR) <- X_ACR_dat_t$GeneID
# Preparation of the matrix
Q_ACR <- as.matrix(Q_ACR)
X_SCI <- SCI_dat_int
# Convert into matrix form
X_SCI <- as.matrix(X_SCI)
# Matrix multiplication of the data matrices
P_ACR_SCI <- X_SCI %*% Q_ACR
# Make the SCI-ACR matrix into a data frame
P_ACR_SCI_DF <- as.data.frame(P_ACR_SCI)
# Move the row names into the first column
P_ACR_SCI_DF <- tibble::rownames_to_column(P_ACR_SCI_DF)
colnames(P_ACR_SCI_DF)[1] <- "Condition"
# make numeric conditions 0=sham 1=sci for regressions
P_ACR_SCI_DF$Condition <- c(rep(0, 5), rep(1, 5))
```

```{r Regression Analysis}
# Initialize vector to store p-values
pc_cols <- paste0("PC", 1:6)
pvals <- numeric(length(pc_cols))
names(pvals) <- pc_cols
# Loop through PCs
for (i in seq_along(pc_cols)) {
  pc <- pc_cols[i]
  # Wilcoxon test between Condition 0 vs 1
  test <- wilcox.test(P_ACR_SCI_DF[[pc]] ~ P_ACR_SCI_DF$Condition)
  # Store raw p-value
  pvals[i] <- test$p.value
}
# Apply BH correction
p.adjusted <- p.adjust(pvals, method = "BH")
# Combine into a dataframe
pc_results <- data.frame(
  PC = pc_cols,
  p_value = pvals,
  p_adj = p.adjusted
)
pc_results$neglog10FDR <-  -log10(pc_results$p_adj)
pc_results$PC <- factor(pc_results$PC, levels = rev(pc_results$PC))
# Horizontal bar plot for the adjusted p values
ggplot(pc_results, aes(x = neglog10FDR, y = PC)) +
  geom_col(colour = "black", width = 0.9, alpha = 1, fill = "skyblue") +
  theme_classic() + 
  labs(x = "-log10(BH-adjusted p-value)", y = "PC") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 16, face = "bold"))
#ggsave("PCselection.svg", plot = PCselection, width = 6, height = 4, units = "in")
```

```{r Percent Var Exp of acrolein in SCI conditions, warning=FALSE}
Q_all <- Q_ACRdat_pr$x
# Percent variance explained in human
SCIVarExp <- lapply(1:ncol(Q_all), function(x) (t(Q_all[,x])%*%t(X_SCI)%*%X_SCI%*%Q_all[,x]) / (sum(diag(t(Q_all)%*%t(X_SCI)%*%X_SCI%*%Q_all))))
# Code does qi^T[X^T*X]qi / diag(Q^T*X^T*X*Q)
# Extract the mouse percent variance explained
mouseVarExp <- as.data.frame(cumVar)
mouseVarExp <- mouseVarExp %>%
  mutate(cumVar = ifelse(row_number() == 1, cumVar, cumVar - lag(cumVar)))
mouseVarExp <- mouseVarExp %>%
  slice(1:PC_80_val)
SCIVarExp <- unlist(SCIVarExp)
SCIVarExp <- as.data.frame(SCIVarExp)
# Combine the SCI and mouse percent variance explained
SCIVarExp <- SCIVarExp %>%
  slice(1:PC_80_val)
PCAvar <- cbind(mouseVarExp, SCIVarExp)
PCAvar <- as.data.frame(PCAvar)
#PCAvar <- PCAvar[c(2,4)]
PCAvar <- rownames_to_column(PCAvar)
# Rename the columns to match respective information
colnames(PCAvar)[1] <- "PC"
colnames(PCAvar)[2] <- "ACR_PC"
colnames(PCAvar)[3] <- "SCI_PC"
# Make the columns numeric
PCAvar$ACR_PC <- as.numeric(PCAvar$ACR_PC)
PCAvar$SCI_PC <- as.numeric(PCAvar$SCI_PC)
PCAvar$ACR_PC <- PCAvar$ACR_PC*100
PCAvar$SCI_PC <- PCAvar$SCI_PC*100
# Keep only the PCs used from the ACR PCA space
PCAvar <- PCAvar[1:PC_80_val, ]
# Prepare the plot for ACR and SCI PC var explained
# Plot of the PCs
p1 <- ggplot(PCAvar, aes(x = SCI_PC, y = ACR_PC)) +
  geom_point(color = "black", size = 2.0) +  # Change point color and size
  labs(title = "PCA",
       x = "Percent Variance Explained in SCI by ACR",
       y = "Percent Variance Explained in ACR") +
  theme_bw() + theme(panel.grid=element_blank()) + scale_x_continuous(limits = c(0, 50)) + scale_y_continuous(limits = c(0, 50)) 
# Plot to identify the PCs in the scatter plot space
ggplot(PCAvar, aes(x = SCI_PC, y = ACR_PC, label = PC)) +
  geom_point(color = "black", size = 2.0) +
  geom_text(hjust = 0, vjust = 0, size = 3) +
  labs(title = "PCA",
       x = "Percent Variance Explained in SCI by ACR",
       y = "Percent Variance Explained in ACR") +
  theme_bw() + theme(panel.grid = element_blank()) +
  scale_x_continuous(limits = c(0, 60)) +
  scale_y_continuous(limits = c(0, 60)) + 
  theme(aspect.ratio=1)
#ggsave("VarExpPlotTransCompR.svg", plot = VarExpPlot, width = 6, height = 4, units = "in")
```

```{r Plotting the Projected Data}
P_ACR_SCI_DF$Condition <- as.factor(P_ACR_SCI_DF$Condition)
# Create ggplot of the different PCs from TransComp-R
g2 <- ggplot(P_ACR_SCI_DF, aes(x = PC1, y = PC3, color = Condition)) + 
  geom_point(shape = 16, size = 2.0, color = "black") + 
  geom_point(size = 2.0) +
  scale_color_manual(values = c("#4d9221", "#c51b7d")) +
  theme(legend.position = 'right') +
  coord_equal() 
# Factorize the Clinical Stages
g2$dataType <- as.factor(g2$data$Condition)
# Plot the figure
g2 +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),   # Remove minor gridlines
    aspect.ratio = 1
  )
#ggsave("PC1PC3_TransCompR.svg", plot = PC1PC3_TransCompR, width = 6, height = 4, units = "in")

# Create ggplot of the different PCs from TransComp-R
g2 <- ggplot(P_ACR_SCI_DF, aes(x = PC5, y = PC6, color = Condition)) + 
  geom_point(shape = 16, size = 2.0, color = "black") + 
  geom_point(size = 2.0) +
  scale_color_manual(values = c("#4d9221", "#c51b7d")) +
  theme(legend.position = 'right') +
  coord_equal() 
# Factorize the Clinical Stages
g2$dataType <- as.factor(g2$data$Condition)
# Plot the figure
g2 +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),   # Remove minor gridlines
    aspect.ratio = 1
  )
#ggsave("PC5PC6_TransCompR.svg", plot = PC5PC6_TransCompR, width = 6, height = 4, units = "in")
```

```{r Seed Set}
set.seed(1)
```

```{r GENE SET ENRICHMENT ANALYSIS - KEGG PATHWAY}
rn_HALLMARK_sets <- msigdbr(species = "Rattus norvegicus",
                        collection = "H"
                       )
# Move the row names to be in the first column
Q_ACR_GSE <- as.data.frame(Q_ACR)
Q_ACR_GSE <- tibble::rownames_to_column(Q_ACR_GSE)
colnames(Q_ACR_GSE)[1] <- "genelist"
# Prepare a list of PC column names
pc_columns <- grep("PC", colnames(Q_ACR_GSE), value = TRUE)
# Create an empty list to store GSEA results for each PC
gsea_results_list <- list()
# GSEA Analysis
for (pc_col in pc_columns) {
  # Extract gene list for each of the current PC through the for loop
  gene_list <- Q_ACR_GSE[, c("genelist", pc_col)]
  # Sort gene list by values of the loading scores
  gene_list <- gene_list %>% arrange(desc(!!sym(pc_col)))
  # Extract PC values for GSEA analysis
  pc_gene_list <- gene_list[[pc_col]]
  names(pc_gene_list) <- gene_list$genelist
  # Run the GSEA analysis
  gsea_results <- GSEA(
    geneList = pc_gene_list,
    minGSSize = 5,
    maxGSSize = 500,
    pvalueCutoff = 0.8,
    eps = 0,
    seed = TRUE,
    pAdjustMethod = "BH", # Benjamini-Hochberg correction factor
    TERM2GENE = dplyr::select(rn_HALLMARK_sets, gs_name, gene_symbol)
  )
  # Store GSEA results in the list
  gsea_results_list[[pc_col]] <- data.frame(gsea_results@result)
}
# Save for kegg pathway
hallmark_gsea_results_list <- gsea_results_list
```

```{r KEGG Results, fig.height=6}
# Select the GSEA results
ACR_PC1_HALLMARK <- hallmark_gsea_results_list$PC1
# Remove the Data Below FDR of 0.05
ACR_PC1_HALLMARK  <- ACR_PC1_HALLMARK [with(ACR_PC1_HALLMARK , !((p.adjust >= 0.05))), ]
Proc_ACR_PC1_HALLMARK <- ACR_PC1_HALLMARK %>% mutate(sign = NES <= 0)
# Adjust the positions on the bar chart to display bars from lowest NES value to largest value
arranged_position <- arrange(Proc_ACR_PC1_HALLMARK, desc(NES))
# Pull out the positions for the enrichment plot
positions <- arranged_position$Description
# Creating the horizontal bar plots
ggplot(Proc_ACR_PC1_HALLMARK) +
  geom_col(aes(x = NES, y = Description, fill=sign), colour = "black", width = 0.9, alpha = 1) + 
  ylab(NULL) + xlab("Normalized Enrichment Score") + theme_minimal() + 
  theme(legend.position = "none", text=element_text(color="black", size = 2), 
        axis.text = element_text(color = "black", size=10)) + theme_classic() + 
geom_vline(xintercept = 0, color = "black", linetype = "solid", linewidth = 1.5) +
  xlim(c(-4.5,4.5)) + scale_y_discrete(limits = positions) + scale_fill_manual(values = c("royalblue", "royalblue"))
#dev.off()
```

```{r KEGG}
# Adjust the positions on the bar chart to display bars from lowest NES value to largest value
arranged_position <- arrange(Proc_ACR_PC1_HALLMARK, desc(NES))
# Pull out the positions for the enrichment plot
positions <- arranged_position$Description
# Define dynamic range for circle size
min_circle_size <- 2   # Smallest circle size
max_circle_size <- 6   # Largest circle size
fixed_breaks <- c(5, 25, 50, 75, 100)  # Consistent breaks for gene size
# Create the GSEA plot
ggplot(data = Proc_ACR_PC1_HALLMARK, aes(x = NES, y = reorder(Description, NES), size = setSize, color = p.adjust)) +
  geom_point(alpha = 1) +
  scale_size_continuous(name = "Set Size",
        range = c(min_circle_size, max_circle_size), 
        breaks = fixed_breaks,                  
        labels = fixed_breaks                    
                 ) +
  scale_color_gradient(name = "adj p-value",
                       low = "#bd0026",
                       high = "#ffffb2",
                       limits = c(0, 0.05)
                       ) +
  labs(x = "Normalized Enrichment Score (NES)",
       y = NULL
      ) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 10),
        plot.title = element_text(hjust = 0.5),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_line(color = "black", linewidth = 0.25, linetype = "dotted"),
        panel.grid.major.x = element_blank(),
        aspect.ratio = 4
       ) +
  xlim(-3, 3) + 
  geom_vline(xintercept = 0, color = "black", linetype = "dashed", linewidth = 0.5)
#ggsave("PC1gsea_hallmark_TransCompR.svg", plot = gsea_hallmark_TransCompR, width = 6, height = 4, units = "in")
```

```{r GENE SET ENRICHMENT ANALYSIS - KEGG PATHWAY}
rn_KEGG_sets <- msigdbr(species = "Rattus norvegicus",
                        collection = "C2"
                       )
rn_KEGG_sets <- rn_KEGG_sets[grepl("CP:KEGG_LEGACY", rn_KEGG_sets$gs_subcollection), ]
# Move the row names to be in the first column
Q_ACR_GSE <- as.data.frame(Q_ACR)
Q_ACR_GSE <- tibble::rownames_to_column(Q_ACR_GSE)
colnames(Q_ACR_GSE)[1] <- "genelist"
# Prepare a list of PC column names
pc_columns <- grep("PC", colnames(Q_ACR_GSE), value = TRUE)
# Create an empty list to store GSEA results
gsea_results_list <- list()
# GSEA Analysis
for (pc_col in pc_columns) {
  # Extract gene list
  gene_list <- Q_ACR_GSE[, c("genelist", pc_col)]
  # Sort gene list by values of the loading scores
  gene_list <- gene_list %>% arrange(desc(!!sym(pc_col)))
  # Extract PC values for GSEA analysis
  pc_gene_list <- gene_list[[pc_col]]
  names(pc_gene_list) <- gene_list$genelist
  # Run the GSEA analysis
  gsea_results <- GSEA(
    geneList = pc_gene_list,
    minGSSize = 5,
    maxGSSize = 500,
    pvalueCutoff = 0.8,
    eps = 0,
    seed = TRUE,
    pAdjustMethod = "BH", # Benjamini-Hochberg correction factor
    TERM2GENE = dplyr::select(rn_KEGG_sets, gs_name, gene_symbol)
  )
  # Store GSEA results in the list
  gsea_results_list[[pc_col]] <- data.frame(gsea_results@result)
}
# Save for kegg pathway
kegg_gsea_results_list <- gsea_results_list
```

```{r KEGG Results, fig.height=6}
ACR_PC1_KEGG <- kegg_gsea_results_list$PC1
# Remove the Data Below FDR of 0.05
ACR_PC1_KEGG  <- ACR_PC1_KEGG [with(ACR_PC1_KEGG , !((p.adjust >= 0.05))), ]
Proc_ACR_PC1_KEGG <- ACR_PC1_KEGG %>% mutate(sign = NES <= 0)
# Adjust the positions on the bar chart to display bars from lowest NES value to largest value
arranged_position <- arrange(Proc_ACR_PC1_KEGG, desc(NES))
# Pull out the positions for the enrichment plot
positions <- arranged_position$Description
# Creating the horizontal bar plots
ggplot(Proc_ACR_PC1_KEGG) +
  geom_col(aes(x = NES, y = Description, fill=sign), colour = "black", width = 0.9, alpha = 1) + 
  ylab(NULL) + xlab("Normalized Enrichment Score") + theme_minimal() + 
  theme(legend.position = "none", text=element_text(color="black", size = 2), 
        axis.text = element_text(color = "black", size=10)) + theme_classic() + 
geom_vline(xintercept = 0, color = "black", linetype = "solid", linewidth = 1.5) +
  xlim(c(-4.5,4.5)) + scale_y_discrete(limits = positions) + scale_fill_manual(values = c("royalblue", "royalblue"))
#dev.off()
```

```{r KEGG}
# Adjust the positions on the bar chart to display bars from lowest NES value to largest value
arranged_position <- arrange(ACR_PC1_KEGG, desc(NES))
# Pull out the positions for the enrichment plot
positions <- arranged_position$Description

# Define dynamic range for circle size
min_circle_size <- 2   # Smallest circle size
max_circle_size <- 6   # Largest circle size
fixed_breaks <- c(5, 25, 50, 75, 100)  # Consistent breaks for gene size

# Create the GSEA plot
ggplot(data = ACR_PC1_KEGG, aes(x = NES, y = reorder(Description, NES), size = setSize, color = p.adjust)) +
  geom_point(alpha = 1) +
  scale_size_continuous(name = "Set Size",
        range = c(min_circle_size, max_circle_size), 
        breaks = fixed_breaks,                    
        labels = fixed_breaks         
                 ) +
  scale_color_gradient(name = "adj p-value",
                       low = "#bd0026",
                       high = "#ffffb2",
                       limits = c(0, 0.05) 
                       ) +
  labs(x = "Normalized Enrichment Score (NES)",
       y = NULL
      ) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 10),
        plot.title = element_text(hjust = 0.5),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_line(color = "black", linewidth = 0.25, linetype = "dotted"),
        panel.grid.major.x = element_blank(),
        aspect.ratio = 4
       ) +
  xlim(-3, 3) + 
  geom_vline(xintercept = 0, color = "black", linetype = "dashed", linewidth = 0.5)
#ggsave("PC1gsea_kegg_TransCompR.svg", plot = gsea_kegg_TransCompR, width = 6, height = 4, units = "in")
```

```{r GENE SET ENRICHMENT ANALYSIS - REACTOME PATHWAY}
rn_REACTOME_sets <- msigdbr(species = "Rattus norvegicus",
                        collection = "C2", subcollection = "CP:REACTOME"
                       )
# Move the row names
Q_ACR_GSE <- as.data.frame(Q_ACR)
Q_ACR_GSE <- tibble::rownames_to_column(Q_ACR_GSE)
colnames(Q_ACR_GSE)[1] <- "genelist"
# Prepare a list of PC column names
pc_columns <- grep("PC", colnames(Q_ACR_GSE), value = TRUE)
# Create an empty list
gsea_results_list <- list()
# GSEA Analysis
for (pc_col in pc_columns) {
  # Extract gene list for each of the current PC through the for loop
  gene_list <- Q_ACR_GSE[, c("genelist", pc_col)]
  # Sort gene list by values of the loading scores
  gene_list <- gene_list %>% arrange(desc(!!sym(pc_col)))
  # Extract PC values for GSEA analysis
  pc_gene_list <- gene_list[[pc_col]]
  names(pc_gene_list) <- gene_list$genelist
  # Run the GSEA analysis
  gsea_results <- GSEA(
    geneList = pc_gene_list,
    minGSSize = 5,
    maxGSSize = 500,
    pvalueCutoff = 0.8, 
    eps = 0,
    seed = TRUE,
    pAdjustMethod = "BH", # Benjamini-Hochberg correction factor
    TERM2GENE = dplyr::select(rn_REACTOME_sets, gs_name, gene_symbol)
  )
  # Store GSEA results in the list
  gsea_results_list[[pc_col]] <- data.frame(gsea_results@result)
}
# Save for kegg pathway
reactome_gsea_results_list <- gsea_results_list
```

```{r Reactome Results, fig.height=6}
ACR_PC1_REACTOME <- reactome_gsea_results_list$PC1
# Remove the Data Below FDR of 0.05
ACR_PC1_REACTOME  <- ACR_PC1_REACTOME [with(ACR_PC1_REACTOME , !((p.adjust >= 0.05))), ]
Proc_ACR_PC1_REACTOME <- ACR_PC1_REACTOME %>% mutate(sign = NES <= 0)
# Adjust the positions on the bar chart to display bars from lowest NES value to largest value
arranged_position <- arrange(Proc_ACR_PC1_REACTOME, desc(NES))
# Pull out the positions for the enrichment plot
positions <- arranged_position$Description
# Creating the horizontal bar plots
ggplot(Proc_ACR_PC1_REACTOME) +
  geom_col(aes(x = NES, y = Description, fill=sign), colour = "black", width = 0.9, alpha = 1) + 
  ylab(NULL) + xlab("Normalized Enrichment Score") + theme_minimal() + 
  theme(legend.position = "none", text=element_text(color="black", size = 2), 
        axis.text = element_text(color = "black", size=10)) + theme_classic() + 
geom_vline(xintercept = 0, color = "black", linetype = "solid", linewidth = 1.5) +
  xlim(c(-4.5,4.5)) + scale_y_discrete(limits = positions) + scale_fill_manual(values = c("royalblue", "royalblue"))
#dev.off()
```

```{r GENE SET ENRICHMENT ANALYSIS - GOBP PATHWAY}
rn_GOBP_sets <- msigdbr(species = "Rattus norvegicus",
                        collection = "C5", subcollection = "GO:BP"
                       )
# Move the row names to be in the first column
Q_ACR_GSE <- as.data.frame(Q_ACR)
Q_ACR_GSE <- tibble::rownames_to_column(Q_ACR_GSE)
colnames(Q_ACR_GSE)[1] <- "genelist"
# Prepare a list of PC column names
pc_columns <- grep("PC", colnames(Q_ACR_GSE), value = TRUE)
# Create an empty list
gsea_results_list <- list()
# GSEA Analysis
for (pc_col in pc_columns) {
  # Extract gene list
  gene_list <- Q_ACR_GSE[, c("genelist", pc_col)]
  # Sort gene list by values of the loading scores
  gene_list <- gene_list %>% arrange(desc(!!sym(pc_col)))
  # Extract PC values for GSEA analysis
  pc_gene_list <- gene_list[[pc_col]]
  names(pc_gene_list) <- gene_list$genelist
  # Run the GSEA analysis
  gsea_results <- GSEA(
    geneList = pc_gene_list,
    minGSSize = 5,
    maxGSSize = 500,
    pvalueCutoff = 0.8, 
    eps = 0,
    seed = TRUE,
    pAdjustMethod = "BH", # Benjamini-Hochberg correction factor
    TERM2GENE = dplyr::select(rn_GOBP_sets, gs_name, gene_symbol)
  )
  # Store GSEA results in the list
  gsea_results_list[[pc_col]] <- data.frame(gsea_results@result)
}
# Save for kegg pathway
gobp_gsea_results_list <- gsea_results_list
```

```{r GOBP Results, fig.height=6}
ACR_PC1_GOBP <- gobp_gsea_results_list$PC1
# Remove the Data Below FDR of 0.05
ACR_PC1_GOBP  <- ACR_PC1_GOBP [with(ACR_PC1_GOBP , !((p.adjust >= 0.05))), ]
Proc_ACR_PC1_GOBP <- ACR_PC1_GOBP %>% mutate(sign = NES <= 0)

# Adjust the positions on the bar chart to display bars from lowest NES value to largest value
arranged_position <- arrange(Proc_ACR_PC1_GOBP, desc(NES))
# Pull out the positions for the enrichment plot
positions <- arranged_position$Description

# Creating the horizontal bar plots
ggplot(Proc_ACR_PC1_GOBP) +
  geom_col(aes(x = NES, y = Description, fill=sign), colour = "black", width = 0.9, alpha = 1) + 
  ylab(NULL) + xlab("Normalized Enrichment Score") + theme_minimal() + 
  theme(legend.position = "none", text=element_text(color="black", size = 2), 
        axis.text = element_text(color = "black", size=10)) + theme_classic() + 
geom_vline(xintercept = 0, color = "black", linetype = "solid", linewidth = 1.5) +
  xlim(c(-4.5,4.5)) + scale_y_discrete(limits = positions) + scale_fill_manual(values = c("royalblue", "royalblue"))
#dev.off()
```



********************** END OF SCRIPT **********************

